[Commands]
switch = handle_gpio_command, "<pin#> <on|off> : set gpio pin high/low (IN GPIOs only in mocked mode)"
dmx = handle_dmx, "send command to DMX controller (type 'dmx' for help)"
motor = handle_motor, "motor [init|<motor_number> <rotation> <speed>]: control motors (type 'motor' for help)"
start_button = handle_start_button, "<enable|disable> : enable/disable start button handling"
audio = handle_audio, "[music_volume|sfx_volume|fadeout|play_music|play_sfx|play_song] <args>: audio commands (type 'audio' for help)"
random_actions = handle_random_actions, "<enable|disable> : enable or disable random actions"
logger = handle_logger, "[queue <enable|disable>] [<info|debug>]: manage logger verbosity and queuing"

sequence = handle_sequence, "[play|stop|validate|upload <filename> <content>]: manage sequences"
mode = handle_mode, "[execute <mode_name>|list|validate|upload <filename> <content>]: manage modes"

metrics = handle_metrics, "<show> : display system metrics"

l = handle_load_configuration, "reload dunebugger conf"
