[General]
arduinoConnected = False
arduinoSerialPort = /dev/ttyUSB0
bouncingTreshold = 0.15
startButtonBouncetimeMillis = 150
eastereggEnabled = True
randomActionsMinSecs = 5
randomActionsMaxSecs = 12
sequenceFolder = /opt/dunebugger-data/sequences/onair
modesFolder = /opt/dunebugger-data/modes
playFile = main.seq
randomElementsFile = random_elements
startButtonGPIOName =  In_StartButton

[MessageQueue]
mQueueEnabled = True
mQueueServers = nats://nats-server:4222
mQueueClientID = core
mQueueSubjectRoot = dunebugger
mQueueStateCheckIntervalSecs = 2
mQueueCyclePlayingResolutionSecs = 10

[Audio]
musicBaseFolder = /opt/dunebugger-data/music
sfxFolder = /opt/dunebugger-data/sfx
vlcdevice = --aout=alsa

[Motors]
motorEnabled = False
motor1Enabled = False
motor2Enabled = False
motor1Freq = 5000
motor2Freq = 5000

[DMX]
dmxEnabled = True
dmxSerialPort = '/dev/ttyUSB0'
dmxBaudRate = 57600

[Log]
dunebuggerLogLevel = DEBUG
sendLogsToQueue = False
