from utils import waituntil
from audio_handler import audioPlayer
from gpio_handler import RPiwrite, RPiToggle
import random

import motor

def setStandBy():
    RPiwrite("SchedaMotori",1)
    RPiwrite("LuceNativita",1)
    RPiwrite("Accensione",1)
    RPiwrite("AlwaysOn",1)
    RPiwrite("DimIngressoEst",1)
    RPiwrite("DimIngressoOvest",1)
    RPiwrite("Case1",1)
    RPiwrite("Case2",1)
    RPiwrite("Case3",1)
    RPiwrite("Fuochi1",1)
    RPiwrite("Fuochi2",1)
    
def testCommands():
    RPiwrite("Accensione",0)
    RPiwrite("DimIngressoEst",0)
    waituntil(12)
    motor.start(1,"ccw",85)
    waituntil(13)
    RPiwrite("Ombre1",1)
    waituntil(36)
    motor.start(2,"ccw",85)
    waituntil(37)
    RPiwrite("Ombre2",1)
    waituntil(40)
    RPiwrite("Ombre1",0)
    waituntil(80)
    RPiwrite("Ombre2",0)
    waituntil(92)
    RPiwrite("DimIngressoEst",1)
    audioPlayer.vstopaudio()
    RPiwrite("Accensione",1)


def sequence():
    RPiwrite("Accensione",0)
    waituntil(5)
    RPiwrite("DimIngressoEst",0)
    RPiwrite("PompaAcqua",1)
    waituntil(12)
    RPiwrite("Case1",0)
    waituntil(13)
    RPiwrite("Case2",0)
    waituntil(15)
    RPiwrite("Fuochi1",0) 
    waituntil(18)
    RPiwrite("Case3",0)
    waituntil(25)
    RPiwrite("Fuochi2",0)
    RPiwrite("LuceNativita",0)
    motor.start(1,"ccw",85)
    waituntil(26)
    RPiwrite("Ombre1",1)
    waituntil(47)
    motor.start(2,"ccw",85)
    waituntil(48)
    RPiwrite("Ombre2",1)
    waituntil(49)
    RPiwrite("Ombre1",0)
    waituntil(71)
    RPiwrite("Ombre2",0)
    RPiwrite("DimIngressoEst",1)
    waituntil(73)
    RPiwrite("LuceNativita",1)
    waituntil(75)
    RPiwrite("Fuochi1",1)
    RPiwrite("Case1",1)
    waituntil(78)
    RPiwrite("Case2",1)
    RPiwrite("Fuochi2",1)
    waituntil(81)
    RPiwrite("Case3",1)
    waituntil(101)
    RPiwrite("PompaAcqua",0)
    audioPlayer.vstopaudio()
    RPiwrite("Accensione",1)

def random_sequence(event):
    randomizable = ["Case1","Case2","Case3","Fuochi1","Fuochi2"]
    rand_elem = random.choice(randomizable)
    RPiToggle(rand_elem)